### PR TITLE
Backend to build schedule page from json

### PR DESCRIPTION
**Pull request by gonzoguajardo**
Let me know what you think about these changes. I separated the frontend (the html code) from the backend (the data that populates the html, in this case your schedule). Now you just have to change the schedule.json file to update the schedule. This prevents you from making html changes accidentally. 

I did have to bring in jQuery (the jquery-3.3.3.min.js file). There is a reason why that file is only on one line. It is called minifcation. We have yet to go over that but for now you don't need to touch that file or worry about what is in it. [ jQuery](http://api.jquery.com/) is a "fast, small, and feature-rich JavaScript library" used my many developers.

### CODE REVIEW

**Comment by gonzoguajardo** [comment]
Ah, I didn't realize you would be concatenating some of those shift variables. So you would be adding like "s1" and "sh4" to one person's shift right? 

We need to change the `schedule.json` then to make all the day properties an array instead of a string. So you can pass multiple shift properties to the day property. 
```
"monday": ["s1", "sh4"]
```

Or we could maybe do something else creative. I will think about this.

**Comment by geodrummer** [comment]
arrays can work

**Comment by gonzoguajardo** [comment]
But then that would be kind of a pain to update if it was an array. 

Maybe we can put a token in the string.  So something like this? And then make an array in the JavaScript from the string? Which one would be easier for you? 
```
"monday": "sh1-sh4"
```

**Comment by geodrummer** [comment]
i mean we can also just change the shift vars to equal something like this`s1pb = "Scorekeeping F1 Pinto Boys` it may take time doing it the first time but at least i would only have to do it once

**Comment by gonzoguajardo** [comment]
Yeah, that works as well. Up to you, you will be the one who will be updating that file.

**Comment by geodrummer** [comment]
i dont mind doing that. i can do it right now

**Comment by gonzoguajardo** [comment]
I would fix #14 and #15 before working on this.  That way we can merge js and update the server so your wsbemployees.site will have a home page.

**Comment by geodrummer** [comment]
yeah thats what i was about to do

**Comment by gonzoguajardo** [comment]
@geodrummer When working with branches, you usually want to work with a branch that is not behind master. For instance visit your [branches page](https://github.com/geodrummer/WSB-Site/branches). If you hover over the bar pictured below, you will see that the this branch, the schedule-backend, branch is behind master by 10 commits but is ahead by 3 commits. This means the branch is missing 10 commits that is already in master but also has 3 new commits that are not in master (our json changes that are in this pull request). When you want to merge something into master, you always want it to be ahead of master and not be behind. 
image
So what does that mean for us? We need to merge our latest master changes into our schedule-backend branch. You don't need a pull request to do this merge, usually you only want to create a pull request when merging something INTO MASTER not when you need to merge master INTO SOME-OTHER-BRANCH. 

I want you to try merging master into the schedule-backend branch when you get the chance. 

1. Checkout master. Fetch and pull to make sure you have the latest changes. 
2. Checkout feature/schedule-backend. Fetch and pull to make sure you have the latest changes. 
3. While you have schedule-backend checked out, right click the master branch and there should be an option that says "Merge master into feature/schedule-backend". There will be a conflict for the file WSB_Schedule.html. Lets make sure we get all the changes from feature/schedule-backend since that is the feature we are working on. Master has a stale version of WSB_Schedule.html. When resolving conflicts, this is where you need to be logical. So ask yourself, what changes would we want? The WSB_Schedule.html changes that are in the [master](https://github.com/geodrummer/WSB-Site/blob/master/WSB_Schedule.html) or the [schedule-backend](https://github.com/geodrummer/WSB-Site/blob/feature/schedule-backend/WSB_Schedule.html) branch. Sometimes you will want master, sometimes you will want other-branch. Sometimes maybe even changes from both. That is why it is a conflict, someone manually needs to go in and determine which one is right. Pay special attention to the bottom part or the "output" when resolving the conflict in gitkraken or any software. That is what the final file is going to look like. Let me know if you need help with this. 
image View the changes before committing, it should only be the changes we put in the last couple of pull requests we did (add another email, fix the help page to point to real files, etc). Merge and commit if it looks good.  

4. Compare it to the picture below. It should look almost identical. If it does, you should be good to push. In particular, you are looking for a line that goes from master to the schedule-backend branch. 
image

5. Push your feature/schedule-backend merge commit.

**Pull request closed without merging**
