### PR TITLE
added other supervisor email

### PR DESCRIPTION
**Pull request by geodrummer**
i think i added it right..all i did was put a comma, then the other email in the $webmasters_email

`$webmaster_email = 'broadwaysystem@gmail.com', 'gabe93caballero@gmail.com';`

### CODE REVIEW

**Review by gonzoguajardo — CHANGES_REQUESTED** [review]
Did you even test this? You can't just add code and not test stuff. I get this error now. I don't think you can just add a comma and a new email address.

`Parse error: syntax error, unexpected ',' in C:\Apache24\htdocs\WSB_Send_Mail.php on line 6`

Look at this [page](https://stackoverflow.com/questions/4506078/php-send-mail-to-multiple-email-addresses). I would use an array at the top and then use the implode command at the bottom of the file when you add the array to the mail call. I tested this and it worked for me but I will let you make the changes.

**Comment by geodrummer** [comment]
so instead of 
`$webmaster_email = "broadwaysystem@gmail.com","gabe93caballero@gmali.com"`

the link you sent said to put an array
`$webmaster_email = array("broadwaysystem@gmail.com","gabe93caballero@gmali.com");`

**Comment by gonzoguajardo** [comment]
`"`? You are using `'`. Don't follow everything you read.  Try it out first and see if it works.  Links won't tell you the truth.  Running your code and trying it will.  Get another email address if you want to make sure you send it to both. 

And you don't need the word array.  In php, you can make an array like `$myarray = [ '1', '2'];`

**Comment by geodrummer** [comment]
sorry..i put `"` by habbit of c++...and well i ran 
`$webmaster_email = ['broadwaysystem@gmail.com', 'gabe93caballero@gmail.com'];` 
and no errors came up...i forgot i could run it using coderunner to check for errors...i usually just trial and error the whole thing...which is probably why i get stuck a lot

**Comment by gonzoguajardo** [comment]
And you added implode to the bottom?  I get an error if I just make an array at the top and don't use the implode command with the mail call. Again, just test your code.  Make sure you are actually getting an email when you try this on your machine. 

```
Warning: mail() expects parameter 1 to be string, array given in C:\Apache24\htdocs\WSB_Send_Mail.php on line 73

Warning: Cannot modify header information - headers already sent by (output started at C:\Apache24\htdocs\WSB_Send_Mail.php:73) in C:\Apache24\htdocs\WSB_Send_Mail.php on line 75
```

**Comment by geodrummer** [comment]
yeah..should be on line 73
`mail(impolde(",",$webmaster_email), 'Availablity', $msg, $headers);`

**Comment by gonzoguajardo** [comment]
You have not pushed.  If you did, this pull request would have been updated with your newest changes.

**Comment by geodrummer** [comment]
just wanted to make sure it all worked before i pushed again

**Comment by gonzoguajardo** [comment]
I couldn't stop laughing at your habit joke.  It is a joke right?  you code so much in c++ that you have a habit now? :p

Wait till you work in like 10 different languages. ;)

**Comment by geodrummer** [comment]
i do like 3 projects a week...i got use to putting ' for a char and " for a string

**Comment by gonzoguajardo** [comment]
Still getting an error.  Are you sure you are testing this? You missed a comma. 

`Parse error: syntax error, unexpected '$webmaster_email' (T_VARIABLE), expecting ',' or ')' in C:\Apache24\htdocs\WSB_Send_Mail.php on line 73`

**Comment by geodrummer** [comment]
lol whoops

**Comment by geodrummer** [comment]
i kinda need this done...but i am still trying to figure out how test php correctly

**Review by gonzoguajardo — APPROVED** [review]

**Pull request merged**
